import React, { useState } from 'react';
import useBooking from '../../../../hooks/useBooking';
import useAuth from '../../../../hooks/useAuth';
import Sectiontitle from '../../../../Components/Title/Sectiontitle';
import GiveReview from '../../../../Components/GiveReview/GiveReview';
import { Rating } from '@smastrom/react-rating';

import '@smastrom/react-rating/style.css'
import useAxiosSecure from '../../../../hooks/useAxiosSecure';
import auth from '../../../../Firebase/firebase.config';
import toast from 'react-hot-toast';
import { Link } from 'react-router-dom';
/**
 * Parcel Type,
● Requested Delivery Date,
● Approximate Delivery Date,
● Booking Date(Auto Generated by new Date())
● Delivery Men ID(this property will be updated when Admin
Assigns a Delivery Men),
● Booking Status(There will be pending, on the way, delivered,
returned, cancelled statuses) ,
● Update and Cancel Button.
● Review Button- If the parcel status is delivered, show a review
button.(See Bonus Point 2 For The Additional Guideline)
● Pay Button(See Bonus Point 3 Fo
    response 
 *  "_id": "65630030d46983f799ba43ee",
        "name": "Shahriar Mostafiz",
        "price": "100",
        "email": "shahriarmostafiz19@gmail.com",
        "phone": "1111111",
        "type": "Gadgets",
        "weight": "2",
        "reciever": "Turjo",
        "recieverPhone": "1111111",
        "address": "abc,dhaka,bangladesh",
        "date": "2023-11-28",
        "latitude": "21.121365496",
        "longitude": "21.121365496",
        "status": "pending"
 * **/
const MyParcels = () => {
    const { user, loading } = useAuth()
    const [bookings, isLoadingBooking, refetchBooking] = useBooking()
    // const [rating, setRating] = useState(3);
    const axiosSecure = useAxiosSecure()
    console.log(bookings);
    if (isLoadingBooking || loading) {
        return <h1>loading parcels ... </h1>
    }

    const handleCancel = (id) => {
        axiosSecure.put(`/bookings/update/user/${id}`, { status: "cancelled" })
            .then(res => {
                console.log(res.data);
                if (res.data.modifiedCount > 0) {
                    toast.error("booking was cancelled ")
                }
            })
    }
    const handleUpdate = id => {
        console.log(id, `will be updated soon `)
    }
    const handlePay = id => {
        console.log(id, `will be paid soon `)
    }
    const handleReview = (e, booking) => {
        e.preventDefault()
        // console.log(booking);
        const form = e.target
        const rating = form.rating.value ? parseInt(form.rating.value) : 3
        const reviewText = form.reviewText.value


        const info = {
            user: booking.name,
            userImage: auth?.currentUser?.photoURL,
            reviewDate: new Date(),
            rating,
            reviewText,
            bookingId: booking._id

        }
        console.log(info);
        axiosSecure.put(`/review/${booking.deliverymanId}`, info)
            .then(res => {
                console.log(res.data)
                if (res.data.modifiedCount > 0) {
                    toast.success("review posted")
                }
            })

    }

    // console.log(bookings);

    return (
        <div className='w-full lg:px-4'>
            <Sectiontitle heading={"My Parcels"} ></Sectiontitle>
            <div className="overflow-x-auto w-full">
                <table className="table  w-full">
                    {/* head */}
                    <thead>
                        <tr>
                            <th></th>
                            <th>Type </th>
                            <th>Booking Date  </th>
                            <th>Requested Delivery </th>
                            <th>Aprx. Delivery</th>
                            <th>Status </th>
                            <th>Delivery Man</th>
                            <th>Actions </th>
                        </tr>
                    </thead>
                    <tbody>
                        {
                            bookings?.map((booking, idx) => <tr key={booking._id}>
                                <th>{idx + 1}</th>
                                <td> {booking.type}</td>
                                <td> {booking.bookingDate}</td>
                                <td>{booking.requestedDate}</td>
                                <td>{booking?.aprxDelivery ? booking.aprxDelivery : "N/A"}</td>
                                <td>{booking.status}</td>
                                {/* to be added by admin  */}
                                <td>{booking?.deliverymanId}</td>
                                <td>
                                    {
                                        booking.status === "delivered" ?
                                            <span className='flex gap-2 '>
                                                <button onClick={() => {
                                                    handlePay(booking._id)
                                                }} className={`  btn btn-xs mx-2 btn-warning`}>Pay   </button>

                                                <span>
                                                    {/* You can open the modal using document.getElementById('ID').showModal() method */}
                                                    <button className="btn btn-xs btn-info" onClick={() => document.getElementById(idx).showModal()}>Review </button>
                                                    <dialog id={idx} className="modal modal-bottom sm:modal-middle">
                                                        <div className="modal-box min-h-[400px] ">
                                                            <div className='flex justify-center'>
                                                                <form className='space-y-2 flex flex-col  justify-center' onSubmit={(e) => handleReview(e, booking)}
                                                                >
                                                                    <div className=" ">
                                                                        <img src={auth?.currentUser?.photoURL} className="rounded-2xl w-8 " alt="" />
                                                                        <p className='text-xl font-medium'>{auth?.currentUser?.displayName}</p>
                                                                    </div>

                                                                    <input type="text" name='reviewText' placeholder="Type your review here" className="input input-bordered input-info w-full max-w-xs" />
                                                                    <select defaultValue={""} name='rating' className="select select-bordered w-full max-w-xs">
                                                                        <option disabled value="" >Rating out of 5</option>
                                                                        <option value={5}>5</option>
                                                                        <option value={4}>4</option>
                                                                        <option value={3}>3</option>
                                                                        <option value={2}>2</option>
                                                                        <option value={1}>1</option>

                                                                    </select>
                                                                    <button type='submit' className='btn btn-wide btn-info'>Submit Your Review</button>

                                                                </form>
                                                            </div>

                                                            <div className="modal-action">
                                                                <form method="dialog">
                                                                    {/* if there is a button in form, it will close the modal */}
                                                                    <button className="btn">Close</button>
                                                                </form>
                                                            </div>
                                                        </div>
                                                    </dialog>
                                                </span>
                                            </span> : <span>
                                                {
                                                    booking.status === "pending" ? <span>

                                                        <button onClick={() => {
                                                            handleCancel(booking._id)
                                                        }}
                                                            className={` btn btn-xs mx-2 btn-error`}>Cancel </button>
                                                        <Link to={`/dashboard/updateBooking/${booking._id}`}

                                                            className={` btn  btn-xs btn-warning`}

                                                        >Update  </Link>
                                                    </span> : "Parcel is On the way"
                                                }


                                            </span>
                                    }



                                </td>

                            </tr>
                            )
                        }
                        {/* row 1 */}


                    </tbody>
                </table>
            </div>
        </div>
    );
};

export default MyParcels;